const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "mongodb+srv://Test:test@cluster0.ib19qwv.mongodb.net/?retryWrites=true&w=majority"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "postgresql://krxten_user:obmPS2LoznGw16t91Y32kBdVeTGspnAn@dpg-cqmihb2j1k6c73b12090-a/krxten"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349048546426";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "available" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_08_58_08_03_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjE2LFxuICAgICAgICAxMDksXG4gICAgICAgIDE3OSxcbiAgICAgICAgMjM0LFxuICAgICAgICAzMixcbiAgICAgICAgMjAsXG4gICAgICAgIDE5LFxuICAgICAgICAxMzQsXG4gICAgICAgIDYzLFxuICAgICAgICA5LFxuICAgICAgICAxMDEsXG4gICAgICAgIDg5LFxuICAgICAgICAxMjAsXG4gICAgICAgIDExOCxcbiAgICAgICAgMjM0LFxuICAgICAgICAxOTQsXG4gICAgICAgIDU2LFxuICAgICAgICAxNDAsXG4gICAgICAgIDUsXG4gICAgICAgIDk5LFxuICAgICAgICAxMTYsXG4gICAgICAgIDE4NixcbiAgICAgICAgMTkwLFxuICAgICAgICA5OCxcbiAgICAgICAgMTQwLFxuICAgICAgICAyNTIsXG4gICAgICAgIDg1LFxuICAgICAgICAyNyxcbiAgICAgICAgMTI4LFxuICAgICAgICAxNDcsXG4gICAgICAgIDI1MSxcbiAgICAgICAgOThcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMjAzLFxuICAgICAgICA5MCxcbiAgICAgICAgNTEsXG4gICAgICAgIDEwOSxcbiAgICAgICAgNjcsXG4gICAgICAgIDIyMixcbiAgICAgICAgMTcsXG4gICAgICAgIDE2OCxcbiAgICAgICAgNTYsXG4gICAgICAgIDI0NCxcbiAgICAgICAgMjA1LFxuICAgICAgICA2OCxcbiAgICAgICAgMTA3LFxuICAgICAgICAzOSxcbiAgICAgICAgMTUzLFxuICAgICAgICAyMzAsXG4gICAgICAgIDk1LFxuICAgICAgICA0OCxcbiAgICAgICAgNDMsXG4gICAgICAgIDE5NixcbiAgICAgICAgMTcwLFxuICAgICAgICAyNTEsXG4gICAgICAgIDU2LFxuICAgICAgICAxMTQsXG4gICAgICAgIDIyOCxcbiAgICAgICAgNjcsXG4gICAgICAgIDE1LFxuICAgICAgICAxNzEsXG4gICAgICAgIDE3NixcbiAgICAgICAgMTA3LFxuICAgICAgICA1NyxcbiAgICAgICAgNzlcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwicGFpcmluZ0VwaGVtZXJhbEtleVBhaXJcIjoge1xuICAgIFwicHJpdmF0ZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDEyOCxcbiAgICAgICAgNyxcbiAgICAgICAgMTc0LFxuICAgICAgICA3MCxcbiAgICAgICAgNTAsXG4gICAgICAgIDE3MCxcbiAgICAgICAgMTIxLFxuICAgICAgICAyMTAsXG4gICAgICAgIDgyLFxuICAgICAgICAyNDMsXG4gICAgICAgIDE5LFxuICAgICAgICAxNDYsXG4gICAgICAgIDI0NSxcbiAgICAgICAgMjE5LFxuICAgICAgICAxMDEsXG4gICAgICAgIDM3LFxuICAgICAgICA4LFxuICAgICAgICAxNDUsXG4gICAgICAgIDEwMyxcbiAgICAgICAgNDMsXG4gICAgICAgIDE3OCxcbiAgICAgICAgMTUsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMjUzLFxuICAgICAgICAxNCxcbiAgICAgICAgMjAzLFxuICAgICAgICAyNDUsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTA5LFxuICAgICAgICA4LFxuICAgICAgICAyMDgsXG4gICAgICAgIDk4XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIzMCxcbiAgICAgICAgNzUsXG4gICAgICAgIDEzMixcbiAgICAgICAgNTksXG4gICAgICAgIDIxNSxcbiAgICAgICAgODMsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTI0LFxuICAgICAgICA3MyxcbiAgICAgICAgMTk0LFxuICAgICAgICAyMzgsXG4gICAgICAgIDMzLFxuICAgICAgICAxNjEsXG4gICAgICAgIDE5MCxcbiAgICAgICAgOTMsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMjAsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjIyLFxuICAgICAgICA5LFxuICAgICAgICAxMTEsXG4gICAgICAgIDQ5LFxuICAgICAgICAxOTEsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTQ1LFxuICAgICAgICAyMTcsXG4gICAgICAgIDExOCxcbiAgICAgICAgMTA1LFxuICAgICAgICAxNzcsXG4gICAgICAgIDE0NixcbiAgICAgICAgOTYsXG4gICAgICAgIDE2XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAzMixcbiAgICAgICAgMTIxLFxuICAgICAgICAxNTcsXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTQsXG4gICAgICAgIDIzNCxcbiAgICAgICAgMjE5LFxuICAgICAgICAyNyxcbiAgICAgICAgMjgsXG4gICAgICAgIDIwNixcbiAgICAgICAgMTYwLFxuICAgICAgICAxNTMsXG4gICAgICAgIDM5LFxuICAgICAgICAyMzMsXG4gICAgICAgIDE1LFxuICAgICAgICAxNzMsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMjEsXG4gICAgICAgIDE4OSxcbiAgICAgICAgNzgsXG4gICAgICAgIDExLFxuICAgICAgICA5MCxcbiAgICAgICAgODIsXG4gICAgICAgIDUwLFxuICAgICAgICAzMixcbiAgICAgICAgNzMsXG4gICAgICAgIDE4LFxuICAgICAgICAyNDMsXG4gICAgICAgIDI1NSxcbiAgICAgICAgMjI5LFxuICAgICAgICAyMjMsXG4gICAgICAgIDcxXG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDIwMyxcbiAgICAgICAgODMsXG4gICAgICAgIDIsXG4gICAgICAgIDIyLFxuICAgICAgICA4MixcbiAgICAgICAgMTg1LFxuICAgICAgICAxODEsXG4gICAgICAgIDE2OCxcbiAgICAgICAgMTUsXG4gICAgICAgIDg0LFxuICAgICAgICA4MixcbiAgICAgICAgMTYwLFxuICAgICAgICAxMDcsXG4gICAgICAgIDUsXG4gICAgICAgIDc1LFxuICAgICAgICA2MSxcbiAgICAgICAgMjA0LFxuICAgICAgICA2NyxcbiAgICAgICAgMjgsXG4gICAgICAgIDY4LFxuICAgICAgICAxODcsXG4gICAgICAgIDE0MyxcbiAgICAgICAgNDAsXG4gICAgICAgIDI0MixcbiAgICAgICAgNDMsXG4gICAgICAgIDEzMixcbiAgICAgICAgMTM5LFxuICAgICAgICAxNCxcbiAgICAgICAgMTM5LFxuICAgICAgICAzMCxcbiAgICAgICAgMTA0LFxuICAgICAgICAxMjZcbiAgICAgIF1cbiAgICB9XG4gIH0sXG4gIFwic2lnbmVkUHJlS2V5XCI6IHtcbiAgICBcImtleVBhaXJcIjoge1xuICAgICAgXCJwcml2YXRlXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMTI4LFxuICAgICAgICAgIDU3LFxuICAgICAgICAgIDE3MCxcbiAgICAgICAgICAxNTUsXG4gICAgICAgICAgMTE1LFxuICAgICAgICAgIDE4MSxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDcxLFxuICAgICAgICAgIDYzLFxuICAgICAgICAgIDk1LFxuICAgICAgICAgIDExMixcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgMjMsXG4gICAgICAgICAgOSxcbiAgICAgICAgICAyMTEsXG4gICAgICAgICAgMjIsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICAwLFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICA0MyxcbiAgICAgICAgICAxMjEsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDE2MyxcbiAgICAgICAgICAxNyxcbiAgICAgICAgICAxOTMsXG4gICAgICAgICAgODksXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDkyLFxuICAgICAgICAgIDk3LFxuICAgICAgICAgIDExM1xuICAgICAgICBdXG4gICAgICB9LFxuICAgICAgXCJwdWJsaWNcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxNzgsXG4gICAgICAgICAgNjMsXG4gICAgICAgICAgMTk1LFxuICAgICAgICAgIDc0LFxuICAgICAgICAgIDY0LFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICAxNzcsXG4gICAgICAgICAgMTcwLFxuICAgICAgICAgIDE4MCxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICA3NSxcbiAgICAgICAgICAxODEsXG4gICAgICAgICAgMjI1LFxuICAgICAgICAgIDE1NyxcbiAgICAgICAgICA2OSxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgOTIsXG4gICAgICAgICAgMjIzLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDE5OSxcbiAgICAgICAgICAxMTUsXG4gICAgICAgICAgMTkwLFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDkzLFxuICAgICAgICAgIDExMCxcbiAgICAgICAgICAxMDMsXG4gICAgICAgICAgMTQzLFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDExXG4gICAgICAgIF1cbiAgICAgIH1cbiAgICB9LFxuICAgIFwic2lnbmF0dXJlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMyxcbiAgICAgICAgMyxcbiAgICAgICAgNTgsXG4gICAgICAgIDEwOSxcbiAgICAgICAgMTk0LFxuICAgICAgICAxOTAsXG4gICAgICAgIDY2LFxuICAgICAgICA1OCxcbiAgICAgICAgMTMxLFxuICAgICAgICA3NCxcbiAgICAgICAgMTAxLFxuICAgICAgICA5NCxcbiAgICAgICAgMjMyLFxuICAgICAgICAxNTYsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjEzLFxuICAgICAgICAyMixcbiAgICAgICAgMjA4LFxuICAgICAgICAyMyxcbiAgICAgICAgMjQwLFxuICAgICAgICAxMTEsXG4gICAgICAgIDEwMixcbiAgICAgICAgMyxcbiAgICAgICAgOTEsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMTksXG4gICAgICAgIDIyOSxcbiAgICAgICAgMTI0LFxuICAgICAgICAyMyxcbiAgICAgICAgMTAyLFxuICAgICAgICAyMjQsXG4gICAgICAgIDYxLFxuICAgICAgICAxOSxcbiAgICAgICAgMjA5LFxuICAgICAgICAyNCxcbiAgICAgICAgMTE5LFxuICAgICAgICA4NixcbiAgICAgICAgMjQ5LFxuICAgICAgICAxMjQsXG4gICAgICAgIDE0OCxcbiAgICAgICAgMjA4LFxuICAgICAgICAyMjcsXG4gICAgICAgIDEwNCxcbiAgICAgICAgMTYzLFxuICAgICAgICAxNDgsXG4gICAgICAgIDE3LFxuICAgICAgICAxMzIsXG4gICAgICAgIDE4MSxcbiAgICAgICAgMjM5LFxuICAgICAgICA1OCxcbiAgICAgICAgMTE4LFxuICAgICAgICA2NixcbiAgICAgICAgOSxcbiAgICAgICAgMTA5LFxuICAgICAgICA4MixcbiAgICAgICAgMTAyLFxuICAgICAgICA4MSxcbiAgICAgICAgNzgsXG4gICAgICAgIDIzNixcbiAgICAgICAgMTc3LFxuICAgICAgICAxODQsXG4gICAgICAgIDI0OCxcbiAgICAgICAgODMsXG4gICAgICAgIDRcbiAgICAgIF1cbiAgICB9LFxuICAgIFwia2V5SWRcIjogMVxuICB9LFxuICBcInJlZ2lzdHJhdGlvbklkXCI6IDE4NixcbiAgXCJhZHZTZWNyZXRLZXlcIjogXCJsTUdwMWtoZzd0SjIxUGovZFRmdFFMaENMKzgrWUpZUmtsTTRVdnhsVE4wPVwiLFxuICBcInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlc1wiOiBbXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDAsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCItaDVwWWtvLVNvLTdPX0VaYTJjbVJRXCIsXG4gIFwicGhvbmVJZFwiOiBcIjhmMThlMzg0LThlZWYtNDIwYS04YjU0LTY0MDdiODNiNDNmM1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAyMjEsXG4gICAgICA2NCxcbiAgICAgIDE5NSxcbiAgICAgIDE1MyxcbiAgICAgIDIxMyxcbiAgICAgIDIzNyxcbiAgICAgIDk0LFxuICAgICAgMTMxLFxuICAgICAgMTc4LFxuICAgICAgMTA1LFxuICAgICAgMjAwLFxuICAgICAgMTE3LFxuICAgICAgNjEsXG4gICAgICAxNDksXG4gICAgICAxNTUsXG4gICAgICAxMSxcbiAgICAgIDEyNSxcbiAgICAgIDIzNyxcbiAgICAgIDM1LFxuICAgICAgMTQ1XG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICAxNzgsXG4gICAgICAzOCxcbiAgICAgIDk4LFxuICAgICAgNjYsXG4gICAgICA5NSxcbiAgICAgIDE5MCxcbiAgICAgIDEyMixcbiAgICAgIDc4LFxuICAgICAgMjUyLFxuICAgICAgMTQ4LFxuICAgICAgMjMyLFxuICAgICAgMjUyLFxuICAgICAgMjM4LFxuICAgICAgMTE3LFxuICAgICAgMTA5LFxuICAgICAgMTIwLFxuICAgICAgMTQ2LFxuICAgICAgNzEsXG4gICAgICAxODksXG4gICAgICAxODdcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcImFjY291bnRcIjoge1xuICAgIFwiZGV0YWlsc1wiOiBcIkNKQ3RuL1FGRUxuaXQ3VUdHQUVnQUNnQVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZUtleVwiOiBcIjhTNDVnZjlxNXZmZWNDT2Y5NzNMSG9yZWZpYmxJaDVMekpFWTIzQWZya2c9XCIsXG4gICAgXCJhY2NvdW50U2lnbmF0dXJlXCI6IFwiL0tLSlJSa0JpR042SjdmUTFGVWNjS2R6VEd1c1lHVGlNMVpCYUhmbEszL0p5d3lIRFM2Q2ZDVWZPU09RV1ArRTdkRStoVnRldXZKWGcxV2tRYm8xQUE9PVwiLFxuICAgIFwiZGV2aWNlU2lnbmF0dXJlXCI6IFwiczVDeDZSTnpFeFB5S09jL1cwdUx2eTRZZnV2b3FMTjFqMTAvMC9RT0ZDcEFXMU5lQVlOdDdZMElaNU93eVJEMFB3ZSs5MXRCeXkxRHhobFlwUk9LREE9PVwiXG4gIH0sXG4gIFwibWVcIjoge1xuICAgIFwiaWRcIjogXCIyMzQ5MDQ4NTQ2NDI2OjE4QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIzMTg1NjI1ODk5MDIyMjoxOEBsaWRcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDkwNDg1NDY0MjY6MThAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJkZXZpY2VJZFwiOiAwXG4gICAgICB9LFxuICAgICAgXCJpZGVudGlmaWVyS2V5XCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgNSxcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgNDYsXG4gICAgICAgICAgNTcsXG4gICAgICAgICAgMTI5LFxuICAgICAgICAgIDI1NSxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgMjMwLFxuICAgICAgICAgIDI0NyxcbiAgICAgICAgICAyMjIsXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDM1LFxuICAgICAgICAgIDE1OSxcbiAgICAgICAgICAyNDcsXG4gICAgICAgICAgMTg5LFxuICAgICAgICAgIDIwMyxcbiAgICAgICAgICAzMCxcbiAgICAgICAgICAxMzgsXG4gICAgICAgICAgMjIyLFxuICAgICAgICAgIDEyNixcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMzQsXG4gICAgICAgICAgMzAsXG4gICAgICAgICAgNzUsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICAyNCxcbiAgICAgICAgICAyMTksXG4gICAgICAgICAgMTEyLFxuICAgICAgICAgIDMxLFxuICAgICAgICAgIDE3NCxcbiAgICAgICAgICA3MlxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIyNjc1NTE3LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBTEJJXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFMQkguanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJGUE1rWFJLeW56ZVA5VjY2NmFLZm5jTy9WYllvVG5GVCsyYTNQajFCaTZrPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE1ODU5NjA1OTEsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxCSS5qc29uIjogIntcImtleURhdGFcIjpcImN5a1Y1bDExcnJXQjBJUEIwdFY5aVZTeFllNWVnVkRlS1VmZm11M3gxRVk9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTU4NTk2MDU5MSxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTEJKLmpzb24iOiAie1wia2V5RGF0YVwiOlwidGhObEUxUUV3QjZHT1hLa2FQOGRQZ1JScG93TVJ2bU5SZ0E4bFRjcjBTZz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNTg1OTYwNTkxLFwiY3VycmVudEluZGV4XCI6NSxcImRldmljZUluZGV4ZXNcIjpbMCwzLDQsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTEJLLmpzb24iOiAie1wia2V5RGF0YVwiOlwiNHZreklPbWNPeDA0N1dQSnhQWUkwTnVrazZkRDdmVDFXN3JGcE9kT1R6ND1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNTg1OTYwNTkxLFwiY3VycmVudEluZGV4XCI6NixcImRldmljZUluZGV4ZXNcIjpbMCwzLDUsNl19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTEJMLmpzb24iOiAie1wia2V5RGF0YVwiOlwiMmJyQ3JXc09mQWQxRURLTUJiN2I1b2QzRE02QXNBY3pVamMxMFN6elhhYz1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNTg1OTYwNTkxLFwiY3VycmVudEluZGV4XCI6NyxcImRldmljZUluZGV4ZXNcIjpbMCwzLDUsN119LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTEJNLmpzb24iOiAie1wia2V5RGF0YVwiOlwiQ2JrK2s5NG01MWszY1RMbVg4OCtNdVJKdzE1dEVYbjRMZ2FHUmE2T3NnOD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNTg1OTYwNTkxLFwiY3VycmVudEluZGV4XCI6NyxcImRldmljZUluZGV4ZXNcIjpbMCwzLDddfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxCTi5qc29uIjogIntcImtleURhdGFcIjpcImY0K2p3bTBQYk1JSVZUN0FmT0FkenpqTU9pSXdJSS82aTNqY2JtWXZBNWs9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTU4NTk2MDU5MSxcImN1cnJlbnRJbmRleFwiOjcsXCJkZXZpY2VJbmRleGVzXCI6WzAsM119LFwidGltZXN0YW1wXCI6XCIxNzIyNTg4OTAwMzExXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTEJPLmpzb24iOiAie1wia2V5RGF0YVwiOlwiKzhId2w3VEJrMWlSVDZ4c2JrK3Q2Zzh1QU5TSzBYWkwyUnRiY2dhME9oRT1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxNTg1OTYwNTkxLFwiY3VycmVudEluZGV4XCI6OCxcImRldmljZUluZGV4ZXNcIjpbMCwzXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFMQlAuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJvQlVHbXl1QlZ3U3dGc3ozaGxJR1dmN28vUUMzOVRLb09kWkcvWmV5Y0o4PVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjE1ODU5NjA1OTEsXCJjdXJyZW50SW5kZXhcIjo5LFwiZGV2aWNlSW5kZXhlc1wiOlswLDNdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUxCUS5qc29uIjogIntcImtleURhdGFcIjpcImdVVFdhWkhqVDlNOGVKa3EvdlpJNTJRUXpxNmtXZUNGK1hDUXQydlZNMXM9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTU4NTk2MDU5MSxcImN1cnJlbnRJbmRleFwiOjksXCJkZXZpY2VJbmRleGVzXCI6WzBdfSxcInRpbWVzdGFtcFwiOlwiMTcyMjY3NTQ5NTQwMFwifSIKfQ=="
module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Blufix",
  packname: process.env.PACK_NAME || "4pf",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "Suhail",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "sk-proj-prByDWg93neCj5TZsFgNT3BlbkFJqTrS1RGjYF8k8NoOpaoX",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "private",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "2c375de0f96d53e85561d52fd85abbba";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
